### ISSUE TITLE
I'm running react-native 0.57.8...only certain notifications work

### ISSUE THREAD

**Issue by milesmeow** [mkuczera/react-native-haptic-feedback#27] opened 2019-03-12 20:21 UTC
I tested the different settings on iOS and only these work for me (iPhone6S iOS 12.1.4):
* selection
* impactMedium
* notificationWarning

All settings work on Android

Testing with:
```
const a = ['selection', 'impactLight', 'impactMedium', 'impactHeavy', 'notificationSuccess', 'notificationWarning', 'notificationError']
const rnd_vibration = a[Math.floor(Math.random()*6)]
console.log('vibrate: ', rnd_vibration)
ReactNativeHapticFeedback.trigger(rnd_vibration, true)
```

**Comment by johanolandero** [comment] 2019-03-14 11:50
iPhone 6s is using a weaker taptic engine which doesn't support all the different types. See implementation and description in #26

**Comment by mkuczera** [comment] 2019-03-20 09:03
Due to the intended behaviour, i will close the issue.

**Closed by mkuczera** 2019-03-20 09:03 UTC
