### ISSUE TITLE
[RN 0.74.2] pod install fails on 2.3.0

### ISSUE THREAD

**Issue by alexander126** [mkuczera/react-native-haptic-feedback#128] opened 2024-08-01 16:42 UTC
After adding the package to react-native app pod install fails with the codegen error:
`[!] Invalid `Podfile` file: [!] /Users/user/.nvm/versions/node/v18.20.3/bin/node ./../node_modules/react-native/scripts/generate-codegen-artifacts.js -p /Users/user/rn-app/ios/.. -o /Users/user/rn-app/ios -t ios
`
Someone faced this problem?

**Comment by natioskar** [comment] 2024-08-01 18:33
dupe of https://github.com/mkuczera/react-native-haptic-feedback/issues/127

**Comment by migueldaipre** [comment] 2024-08-01 22:02
Fixed by #129

**Comment by mkuczera** [comment] 2024-08-02 06:47
Merged. Will just invest a little bit time to have a proper testapplication and pipelines to avoid future fails.

**Comment by spookyvert** [comment] 2024-08-02 23:23
i'm seeing this problem as well when using `2.3.0`. theres multiple RN packages thats facing this exact issue.

**Comment by mkuczera** [comment] 2024-08-03 18:20
Can be verified in "2.3.1-next.0".
[npmjs.com/package/react-native-haptic-feedback/v/2.3.1-next.0](https://www.npmjs.com/package/react-native-haptic-feedback/v/2.3.1-next.0)

Would be awesome to have feedback that everything works fine before releasing an official version :)

**Comment by rsml** [comment] 2024-08-04 19:34
@mkuczera Confirmed that 2.3.1-next.0 installs, builds, runs, and works successfully for me on my physical iPhone device. My app doesn't use android so I haven't tested that.

Previously "^2.2.0" (not sure what version it was resolving too) had recently started failing on "pod install".

**Comment by villemuittari** [comment] 2024-08-05 05:34
Installation worked, but got a build error on iOS: 

`node_modules/react-native-haptic-feedback/ios/RNHapticFeedback/RNHapticFeedback.h:3:9 'RNHapticFeedbackSpec.h' file not found`

<img width="736" alt="image" src="https://github.com/user-attachments/assets/5f8a456a-9454-4577-974e-ea3a66cc4e80">

**Comment by mkuczera** [comment] 2024-08-05 07:56
Thanks for the feedback. I will check RNHapticFeedbackSpec. This was adjusted 17 months ago and didn´t remove it. oO

**Comment by mkuczera** [comment] 2024-08-05 18:27
Thank you all. Version 2.3.1 is release. @villemuittari just digged a little bit, but shouldn´t be crucial for any build process of your app. Also tried various configurations. But maybe you can point me to your setup where this error occured (added the spec file, but was working fine also without it)

**Closed by mkuczera** 2024-08-05 18:27 UTC
